[package]
name = "wellwalla"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
az = "1.2.1"
bevy = "0.10.1"
bevy_egui = "0.20.3"
fixed = "1.23.1"
log = "0.4.19"
rand = { version = "0.8.5", features = ["small_rng"] }
rand_distr = "0.4.3"
serde = { version = "1.0.166", features = ["derive"] }
toml = { version = "0.7.5", features = ["display"] }
