[package]
name = "nbody-simd"
version = "0.1.0"
edition = "2024"

[dependencies]
az = "1.2.1"
fixed = "1.28.0"
num-traits = "0.2.19"
sleef = "0.3.2"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "my_benchmark"
harness = false

[workspace]
members = [".", "bev"]
