[package]
name = "bev"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel = "2.3.1"
bevy = { version = "0.15.3", features = ["jpeg"] }
bevy_egui = "0.33.0"
bevy_polyline = "0.11.0"
nbody-simd = {path = ".."}
ordered-float = "5.0.0"
